[build]
  functions = ".netlify/functions/"

[dev]
  publish = "dist"

[[redirects]]
  from = "/:splat"
  to = "/.netlify/functions/:splat"
  query = {url = ":url"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"