[build]
  functions = ".netlify/functions/"

[dev]
  publish = "dist"

[[redirects]]
  from = "/:code"
  to = "/.netlify/functions/:code"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"