[build]
  functions = ".netlify/functions/"

[dev]
  publish = "dist"

# [[redirects]]
#   from = "/:code"
#   to = "/.netlify/functions/:code"
#   status = 200
#   force = true

[[redirects]]
  from = "/splat"
  to = "/.netlify/functions/:splat"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"